# Generated by Django 2.0.5 on 2018-05-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180520_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuarios_registrados',
        ),
    ]
