# Generated by Django 2.0.6 on 2018-07-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_autor_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor_Post',
            field=models.TextField(default='', max_length=20),
        ),
    ]
