# Generated by Django 2.0.6 on 2018-07-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180729_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor_Post',
            field=models.CharField(default='', max_length=20),
        ),
    ]
