# Generated by Django 2.0.6 on 2018-07-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180729_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor_Post',
        ),
    ]
